version: '3.4'

networks:

  backend:
    driver: bridge

services:

  provaf_api:
    image: ${REGISTRY:-provaf}/api:${PLATFORM:-linux}-${TAG:-latest}
    container_name: "provaf_api"
    build:
      context: .
      dockerfile: ProvaF.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DefaultConnection=Host=provaf_database;Port=5432;Database=provaf;Username=provaf_user;Password=S3nh4F0rt3!;
    ports:
      - "5000:80"
    depends_on:
      - provaf_database
    networks: 
      - backend 
        
  provaf_database:
    image: "postgres"
    container_name: "provaf_database"
    environment:
      - POSTGRES_USER=provaf_user
      - POSTGRES_PASSWORD=S3nh4F0rt3!
      - POSTGRES_DB=provaf
    ports:
      - "5432:5432"
    networks: 
      - backend
    #volumes:
      #- ./pg-data:/var/lib/postgresql/data
