version: '3.4'

services:

  db:
    image: "postgres"
    container_name: "postgres_docker"
    environment:
      - POSTGRES_USER=provaf_user
      - POSTGRES_PASSWORD="S3nh4F0rt3!"
      - POSTGRES_DB=provaf
    ports:
      - "54321:5432"
    #volumes:
      #- ./pg-data:/var/lib/postgresql/data